repository_type: pipeline

nf_core_version: 3.3.0.dev0

lint: {}

template:
  org: nf-core
  name: cattype
  description: ufhskdfjasklfjslf
  author: wojfwpoeijfdrjgfsweodfk
  version: 0.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
